// Shared constants for all Cloud Functions.
// Source of truth for economy rules — keep in sync with src/constants/economy.js.

// Crew rosters and mission economy values come from the synced copy of
// src/crews.js (functions/crews.js is generated by `npm run sync:chars`).
const {
  CREWS, CREW_MISSION_REWARDS, CREW_CONTRIB,
  getCrewBuyTarget, getCrewSellTarget, getCrewVolumeTarget,
  CREW_UNDERDOG_MULT_MAX, CREW_REJOIN_LOCKOUT_DAYS, CREW_SWITCH_PENALTY,
} = require('./crews');

// ============================================
// MARKET MECHANICS
// ============================================
const BASE_IMPACT = 0.012;
const BASE_LIQUIDITY = 100;
const BID_ASK_SPREAD = 0.002;
const ETF_BID_ASK_SPREAD = 0.001;
const MIN_PRICE = 0.01;
const DUST_MAX_VALUE = 5; // positions worth less than this ($) are sweepable dust
const MAX_PRICE_CHANGE_PERCENT = 0.05;

// Anti-manipulation: per-user, per-ticker, per-day limits
const MAX_DAILY_IMPACT = 0.10;          // 10% max cumulative price move
const MAX_TRADES_PER_TICKER_24H = 10;   // Max buys or sells per ticker per rolling 24h

// Admin price protection: after an admin manually sets a price, automated
// price movers (bot trader, market maker) leave that ticker alone for this
// long so they can't claw the adjustment back. Resets each time admin re-sets.
const ADMIN_PRICE_PROTECTION_MS = 7 * 24 * 60 * 60 * 1000; // 7 days

// Anti-manipulation: reduced price impact for brand-new accounts.
// Mirrors src/constants/economy.js — keep both in sync.
const NEW_ACCOUNT_IMPACT_PERIOD_DAYS = 3;  // ramps over the first 3 days
const NEW_ACCOUNT_MIN_IMPACT_FACTOR = 0.1; // 10% impact at day 0 → 100% at day 3

// Anti-alt: hard cap on accounts per IP, enforced at signup AND trade.
// ADMIN_UID is always exempt. Flip IP_ACCOUNT_CAP_ENABLED to false to disable the
// hard block instantly (e.g. if client IPs turn out unreliable) without a code change.
const MAX_ACCOUNTS_PER_IP = 2;
const IP_ACCOUNT_CAP_ENABLED = true;
// A deleted account keeps holding its per-IP slot for this long, then the slot
// frees up. Stops the pump → delete → remake loop (a month's wait per cycle makes
// it worthless) while still letting genuine deleters rejoin later.
const IP_SLOT_RELEASE_MS = 30 * 24 * 60 * 60 * 1000; // 30 days
// A Discord account linked to a now-deleted Stockism account is blocked from
// linking or creating a new one for this long. Mirrors IP_SLOT_RELEASE_MS: it
// kills the create → grab the verified $3k starting cash → gamble → delete →
// remake loop (and one aged Discord spawning troll accounts) by making each cycle
// cost a month's wait. The $3k bonus is one-time per live account, so within this
// window it can never be re-granted either.
const DISCORD_RELINK_COOLDOWN_MS = 30 * 24 * 60 * 60 * 1000; // 30 days

const TWENTY_FOUR_HOURS_MS = 24 * 60 * 60 * 1000;
const ONE_WEEK_MS           = 7 * 24 * 60 * 60 * 1000;
const THIRTY_DAYS_MS        = 30 * 24 * 60 * 60 * 1000;
const NINETY_DAYS_MS        = 90 * 24 * 60 * 60 * 1000;

// Read cap for the public-profile sparkline query (keeps per-view Firestore
// reads bounded no matter how many history points an account has).
const PUBLIC_PROFILE_SPARKLINE_MAX_POINTS = 150;

// ============================================
// WEEKLY TRADING HALT (Thursday 13:00–21:00 UTC)
// ============================================
const WEEKLY_HALT_START_MINUTE = 780;  // 13 * 60
const WEEKLY_HALT_END_MINUTE   = 1260; // 21 * 60
const PRE_MARKET_START_MINUTE  = 1230; // 20:30 UTC
const PRE_MARKET_LOCK_MINUTE   = 1255; // 20:55 UTC — no placements or cancellations after this; auction settles 20:56
// Max-buy headroom for pre-market orders: opening ask can sit up to ~5%
// (auction impact cap) + spread above the queue-time price, so placement
// validates against price * this buffer. Keep in sync with src/constants/economy.js.
const PRE_MARKET_MAX_BUY_BUFFER = 1.06;
// A single ticker's total short value (existing + new) can't exceed this
// fraction of portfolio equity.
const SHORT_CONCENTRATION_CAP = 0.5;

const isWeeklyTradingHalt = () => {
  const now = new Date();
  if (now.getUTCDay() !== 4) return false;
  const utcMins = now.getUTCHours() * 60 + now.getUTCMinutes();
  return utcMins >= WEEKLY_HALT_START_MINUTE && utcMins < WEEKLY_HALT_END_MINUTE;
};

// ============================================
// ECONOMY
// ============================================
const STARTING_CASH = 3000;            // full starting cash once verified (Discord linked)
const UNVERIFIED_STARTING_CASH = 1000; // starting cash before Discord verification (anti-alt)
const BAILOUT_CASH = 1500;
const NAME_CHANGE_COST = 10000;        // cash cost to change display name (changeDisplayName)

// Anti-manipulation: cooldown between buy/short on the same ticker by one user.
const TICKER_COOLDOWN_MS = 10000;      // 10 seconds

// Anti-manipulation: executeTrade throttle windows.
const TRADE_COOLDOWN_MS = 3000;               // min gap between any two trades by one user
const TRADE_HOLD_PERIOD_MS = 45 * 1000;       // min hold before a position can be sold/covered
const MAX_TRADES_PER_TICKER_HOUR = 15;        // buy/short velocity cap per ticker per hour
const TRADE_BURST_LIMIT = 3;                  // max buys or shorts per ticker per burst window
const TRADE_BURST_WINDOW_MS = 5 * 60 * 1000;  // 5 minutes
// After this many shorts on one ticker inside the rolling window, further
// shorts must wait for the oldest one to age out.
const MAX_SHORTS_BEFORE_COOLDOWN = 3;
const SHORT_COOLDOWN_WINDOW_MS = 8 * 60 * 60 * 1000; // 8 hours

// Daily check-in streak rewards. Index 0 = day 1. The reward escalates with the
// consecutive-day check-in streak, then caps at the last value forever (as long
// as the streak isn't broken). The streak itself is already tracked as
// checkinStreak. Day 1 stays at the old flat $300, so the curve is strictly an
// upgrade for everyone. Keep in sync with src/constants/economy.js.
const CHECKIN_STREAK_REWARDS = [300, 325, 350, 375, 400, 425, 500];
const SHORT_MARGIN_RATIO = 1.0; // 100% collateral — deposit dollar-for-dollar
const LEADERBOARD_CACHE_TTL = 5 * 60 * 1000; // 5 min — freshness window for the in-memory cache AND the shared leaderboard/{key} doc (keep in sync with LEADERBOARD_DOC_FRESH_MS in src/constants/economy.js)

// ============================================
// MARGIN
// ============================================
const MARGIN_INTEREST_RATE = 0.005;  // 0.5% per day
const MARGIN_CASH_MINIMUM  = 2000;   // min cash to enable margin — keep in sync with src/constants/economy.js
// CREW_SWITCH_PENALTY comes from crews.js (single source shared with the frontend)
const CREW_REJOIN_LOCKOUT_MS = CREW_REJOIN_LOCKOUT_DAYS * TWENTY_FOUR_HOURS_MS; // rejoin lockout after leaving a crew (from crews.js)
const MAX_SHORT_EXPOSURE_RATIO = 1.0; // total short value ≤ net worth (1:1 cap)
const MARKET_OPEN_GRACE_PERIOD_MINUTES = 30; // pause auto-liquidations after halt end
const LADDER_GAME_MAX_BALANCE = 10000; // max cash held in ladder minigame at once
const LADDER_GAME_MAX_DEPOSIT_PER_WINDOW = 10000; // max cash deposited into ladder within the rolling window
const LADDER_DEPOSIT_WINDOW_MS = 12 * 60 * 60 * 1000; // rolling 12h window for the deposit cap
// Crew buy/sell/volume goals scale with roster size (see getCrew*Target in crews.js)

// ============================================
// MARGIN THRESHOLDS
// ============================================
const SHORT_MARGIN_CALL_THRESHOLD    = 0.25; // short equity ratio below which force-cover triggers
const SHORT_MARGIN_DAMPENING_FACTOR  = 0.50; // reduced price impact for forced short covers
const LONG_MARGIN_CALL_THRESHOLD     = 0.30; // long margin equity ratio at which margin call is issued
const LONG_MARGIN_LIQUIDATION_THRESHOLD = 0.25; // long margin equity ratio at which auto-liquidation triggers

// ============================================
// IPO
// ============================================
const IPO_PRICE_JUMP = 0.15; // 15% price bump when IPO fully subscribed
// IPO-bought shares are locked from selling until ipoEndsAt + this buffer, so the
// guaranteed +15% launch pop can't be flipped for a risk-free profit. Measured
// from ipoEndsAt because shares already can't trade before launch: a last-second
// buyer (who triggers an early sellout) still has to hold through the float window,
// and an early buyer holds through the IPO they opted into.
const IPO_SELL_LOCKUP_MS = 24 * 60 * 60 * 1000; // 24 hours
// Shares bought with margin are locked from re-selling this long, so borrowed
// money can't be used to spike a stock and bail before the price reverts.
const MARGIN_SELL_LOCKUP_MS = 36 * 60 * 60 * 1000; // 36 hours

// ============================================
// EVENT PREDICTION MARKETS (long-term, AMM-priced)
// ============================================
// LMSR liquidity parameter (b). Bigger = steadier prices and a larger bounded
// house subsidy. Max the house can ever lose on a market is b * ln(numOutcomes)
// (~$3,466 for a yes/no market at b=5000). Seeded generously on purpose: stable
// prices and generous payouts build trust, and a deep book stops one big early
// bet from yanking the line.
const EVENT_AMM_LIQUIDITY = 5000;
const EVENT_MIN_BUYIN = 1; // minimum dollar cost of a single buy (avoids dust)

// ============================================
// CREW MEMBER MAPPINGS
// ============================================
// Derived from src/crews.js via the synced functions/crews.js — never list
// rosters here by hand (a hand-copied list once drifted and broke missions
// for newly added characters).
const CREW_MEMBERS = {};
Object.values(CREWS).forEach((c) => { CREW_MEMBERS[c.id] = c.members; });

const ALL_CREW_TICKERS = new Set(Object.values(CREW_MEMBERS).flat());

const ANIMAL_TICKERS = new Set(['RYAN', 'EDEN', 'MIRO', 'ENU']);

// Buys below this price count for the Underdog Investor daily mission.
const UNDERDOG_PRICE_THRESHOLD = 20;

// ============================================
// LEADERBOARD
// ============================================
const FOURTEEN_DAYS_MS = 14 * 24 * 60 * 60 * 1000;
const ACTIVE_USER_WINDOW_MS = FOURTEEN_DAYS_MS; // a user counts as "active" if they acted within this window

// ============================================
// ACHIEVEMENTS
// ============================================
// Unifier of Seoul: a character only counts toward the achievement if the user
// holds at least one FULL share. The threshold sits just under 1.0 to tolerate
// floating-point dust from fractional trades (e.g. 0.3333 + 0.6667 landing on
// 0.9999999999999999) while still rejecting any genuine partial holding.
const UNIFIER_FULL_SHARE_MIN = 0.999999;

// ============================================
// LADDER GAME
// ============================================
const LADDER_GAME_INITIAL_BALANCE    = 500;   // starting balance for new ladder game users
const LADDER_MIN_BET                 = 1;     // ladder bets are whole dollars only; decimals are floored away (no decimals = no rounding exploit)
const LADDER_HIGH_BET_THRESHOLD      = 50;    // bets at or above this count toward ADDICTED achievement
const LADDER_ACHIEVEMENT_PROFIT      = 2500;  // net profit needed for COMPULSIVE_GAMBLER achievement
const LADDER_ACHIEVEMENT_HIGH_BETS   = 100;   // high-bet games needed for ADDICTED achievement

// Withdrawal tax — keep in sync with src/constants/economy.js
const LADDER_WITHDRAW_PRINCIPAL_FEE_RATE = 0.05; // flat 5% on the portion that is deposited principal coming back
const LADDER_WITHDRAW_RUSH_RATE          = 0.15; // +15% of the whole withdrawal if any deposit landed within LADDER_DEPOSIT_WINDOW_MS
// Lifetime-progressive brackets over cumulative profit withdrawn (not per-withdrawal,
// so splitting withdrawals can't dodge a bracket). upTo = upper bound of cumulative
// profit withdrawn that the rate applies to.
const LADDER_WITHDRAW_PROFIT_BRACKETS = [
  { upTo: 1000,     rate: 0.15 },
  { upTo: 5000,     rate: 0.30 },
  { upTo: Infinity, rate: 0.45 },
];

// ============================================
// DISCORD ALERTS
// ============================================
const WHALE_ALERT_SHARES_SOFT   = 50;   // shares threshold (combined with price check) for whale alert
const WHALE_ALERT_PRICE_SOFT    = 35;   // price threshold (combined with shares check) for whale alert
const WHALE_ALERT_SHARES_HARD   = 100;  // shares threshold alone triggers whale alert regardless of price
const CREW_MILESTONE_THRESHOLDS = [5, 10, 25, 50, 100]; // crew member counts that trigger Discord alerts

// ============================================
// ADMIN OPS
// ============================================
const REINSTATE_CASH_DEFAULT = 1000; // cash given when admin reinstates a bankrupt user

// ============================================
// MISSION REWARDS
// ============================================
// Daily/weekly mission payouts live on the mission definitions in crews.js
// (claimMissionReward reads them off the assigned mission). Crew mission
// values are re-exported from crews.js below so services keep importing
// everything from this hub.

// ============================================
// ADMIN
// ============================================
// Set via functions/.env in production; fallback for local dev only.
// This is the admin account's Firebase UID — every admin-only function checks against it.
const ADMIN_UID = process.env.ADMIN_UID || '4usiVxPmHLhmitEKH2HfCpbx4Yi1';

// ============================================
// DISCORD CHANNELS
// ============================================
// Channel the daily free-stock drop posts to. Used by discord.js (dailyFreeStock) and
// health.js (discordHealthCheck) — single source of truth so the two can't drift.
const DISCORD_DAILY_DROP_CHANNEL = '1483767343581761658';

// ============================================
// DISCORD DAILY DROP (loot roll in discordInteractions.js)
// ============================================
// "High tier" is defined at roll time by LIVE price (not basePrice, which has
// drifted way below current prices). The priciest fraction of tradeable stocks
// is high tier. In a NORMAL roll a high-tier stock is capped at 1 share so a
// lucky draw can't make someone rich; jackpots are drawn only from high tier.
const DAILY_DROP_JACKPOT_CHANCE = 0.03;            // 3% of claims are jackpots
const DAILY_DROP_HIGH_TIER_FRACTION = 0.25;        // priciest 25% by live price = high tier
const DAILY_DROP_HIGH_TIER_CAP = 1;                // max shares of a high-tier stock in a normal roll
const DAILY_DROP_NORMAL_SHARE_VALUES = [1, 2, 3, 4];
const DAILY_DROP_NORMAL_SHARE_WEIGHTS = [55, 30, 11, 4]; // total shares, heavily weighted to 1-2
const DAILY_DROP_NORMAL_VARIETY_VALUES = [1, 2, 3];
const DAILY_DROP_NORMAL_VARIETY_WEIGHTS = [70, 25, 5];   // how many different stocks
const DAILY_DROP_JACKPOT_SHARES_MIN = 6;
const DAILY_DROP_JACKPOT_SHARES_MAX = 10;
const DAILY_DROP_JACKPOT_VARIETY_MIN = 3;
const DAILY_DROP_JACKPOT_VARIETY_MAX = 5;

// ============================================
// CLOUD FUNCTION SAFETY CAPS (cost / abuse blast radius)
// ============================================
// Cosmetic catalog — validates shop purchases (purchaseCosmetic) and admin
// grants (adminGrantCosmetic). Keep ids/prices in sync with the frontend list
// in src/constants/cosmetics.js.
const COSMETIC_CATALOG = {
  name_gold:         { type: 'nameColor',   price: 5000  },
  name_crimson:      { type: 'nameColor',   price: 5000  },
  name_emerald:      { type: 'nameColor',   price: 5000  },
  name_sapphire:     { type: 'nameColor',   price: 5000  },
  name_violet:       { type: 'nameColor',   price: 5000  },
  name_rose:         { type: 'nameColor',   price: 5000  },
  name_cyan:         { type: 'nameColor',   price: 5000  },
  name_silver:       { type: 'nameColor',   price: 5000  },
  name_tangerine:    { type: 'nameColor',   price: 5000  },
  glow_gold:         { type: 'rowGlow',     price: 15000 },
  glow_crimson:      { type: 'rowGlow',     price: 15000 },
  glow_neon:         { type: 'rowGlow',     price: 15000 },
  glow_pink:         { type: 'rowGlow',     price: 15000 },
  glow_sapphire:     { type: 'rowGlow',     price: 15000 },
  glow_violet:       { type: 'rowGlow',     price: 15000 },
  glow_cyan:         { type: 'rowGlow',     price: 15000 },
  glow_orange:       { type: 'rowGlow',     price: 15000 },
  glow_silver:       { type: 'rowGlow',     price: 15000 },
  backdrop_royal:    { type: 'rowBackdrop', price: 25000 },
  backdrop_inferno:  { type: 'rowBackdrop', price: 25000 },
  backdrop_frost:    { type: 'rowBackdrop', price: 25000 },
  backdrop_blush:    { type: 'rowBackdrop', price: 25000 },
  backdrop_verdant:  { type: 'rowBackdrop', price: 25000 },
  backdrop_gilded:   { type: 'rowBackdrop', price: 25000 },
  backdrop_midnight: { type: 'rowBackdrop', price: 25000 },
  backdrop_onyx:     { type: 'rowBackdrop', price: 25000 },
  backdrop_lagoon:   { type: 'rowBackdrop', price: 25000 },
  // Animated cosmetics
  name_shimmer:       { type: 'nameColor',   price: 40000  },
  name_aurora:        { type: 'nameColor',   price: 50000  },
  name_rainbow:       { type: 'nameColor',   price: 60000  },
  frame_ember:        { type: 'rowFrame',    price: 80000  },
  frame_frost:        { type: 'rowFrame',    price: 80000  },
  frame_electric:     { type: 'rowFrame',    price: 90000  },
  frame_gold:         { type: 'rowFrame',    price: 120000 },
  glow_pulse_gold:     { type: 'rowGlow',    price: 50000  },
  glow_pulse_crimson:  { type: 'rowGlow',    price: 50000  },
  glow_pulse_neon:     { type: 'rowGlow',    price: 50000  },
  glow_pulse_pink:     { type: 'rowGlow',    price: 50000  },
  glow_pulse_sapphire: { type: 'rowGlow',    price: 50000  },
  glow_pulse_violet:   { type: 'rowGlow',    price: 50000  },
  glow_pulse_cyan:     { type: 'rowGlow',    price: 50000  },
  glow_pulse_orange:   { type: 'rowGlow',    price: 50000  },
  glow_pulse_silver:   { type: 'rowGlow',    price: 50000  },
};

// Crew head ("top dog") — assigned automatically every Monday by
// weeklyCrewRankings: best weekly PERCENTAGE gain among a crew's active
// members (percentage, not dollars, so whales can't sit on the crown).
// The baseline floor stops near-zero accounts from farming huge percentages.
// Dynasty weeks = the streak that earns DYNASTY, and the reign length that
// makes dethroning someone count as USURPER.
const CREW_HEAD_MIN_BASELINE = 1000;
const CREW_HEAD_DYNASTY_WEEKS = 4;

// Minimum 7-day-ago portfolio value to appear on the percent-gain leaderboard.
// Same rationale as CREW_HEAD_MIN_BASELINE: a $50 account doubling up must not
// outrank real portfolios with a meaningless percentage.
const LEADERBOARD_PERCENT_MIN_BASELINE = 1000;

// Hard ceiling on how many copies of any one function can run at the same time.
// Bounds how fast cost can pile up if a function is flooded (deliberate abuse or a
// bug) without affecting normal play. Lower = safer on cost; too low could throttle
// trades at a busy market open. Applied to every function via functions/fnConfig.js.
const MAX_FN_INSTANCES = 10;

// App Check enforcement on callable functions. When true, callables reject any
// request that didn't come from our real app (no valid App Check token), which
// blocks outside scripts from hammering the backend. OFF by default on purpose:
// turn it on ONLY after confirming in Firebase Console → App Check that real
// traffic is ~100% verified, or legitimate players could be locked out. Flip back
// to false to disable instantly without a code change (mirrors IP_ACCOUNT_CAP_ENABLED).
const APP_CHECK_ENFORCED = false;

module.exports = {
  BASE_IMPACT,
  BASE_LIQUIDITY,
  BID_ASK_SPREAD,
  ETF_BID_ASK_SPREAD,
  MIN_PRICE,
  DUST_MAX_VALUE,
  MAX_PRICE_CHANGE_PERCENT,
  MAX_DAILY_IMPACT,
  MAX_TRADES_PER_TICKER_24H,
  ADMIN_PRICE_PROTECTION_MS,
  NEW_ACCOUNT_IMPACT_PERIOD_DAYS,
  NEW_ACCOUNT_MIN_IMPACT_FACTOR,
  MAX_ACCOUNTS_PER_IP,
  IP_ACCOUNT_CAP_ENABLED,
  IP_SLOT_RELEASE_MS,
  DISCORD_RELINK_COOLDOWN_MS,
  TWENTY_FOUR_HOURS_MS,
  ONE_WEEK_MS,
  THIRTY_DAYS_MS,
  PUBLIC_PROFILE_SPARKLINE_MAX_POINTS,
  NINETY_DAYS_MS,
  SHORT_MARGIN_RATIO,
  WEEKLY_HALT_START_MINUTE,
  WEEKLY_HALT_END_MINUTE,
  PRE_MARKET_START_MINUTE,
  PRE_MARKET_LOCK_MINUTE,
  PRE_MARKET_MAX_BUY_BUFFER,
  SHORT_CONCENTRATION_CAP,
  isWeeklyTradingHalt,
  STARTING_CASH,
  UNVERIFIED_STARTING_CASH,
  BAILOUT_CASH,
  NAME_CHANGE_COST,
  TICKER_COOLDOWN_MS,
  TRADE_COOLDOWN_MS,
  TRADE_HOLD_PERIOD_MS,
  MAX_TRADES_PER_TICKER_HOUR,
  TRADE_BURST_LIMIT,
  TRADE_BURST_WINDOW_MS,
  MAX_SHORTS_BEFORE_COOLDOWN,
  SHORT_COOLDOWN_WINDOW_MS,
  CHECKIN_STREAK_REWARDS,
  LEADERBOARD_CACHE_TTL,
  MARGIN_INTEREST_RATE,
  MARGIN_CASH_MINIMUM,
  CREW_SWITCH_PENALTY,
  CREW_REJOIN_LOCKOUT_MS,
  CREW_UNDERDOG_MULT_MAX,
  CREW_HEAD_MIN_BASELINE,
  CREW_HEAD_DYNASTY_WEEKS,
  LEADERBOARD_PERCENT_MIN_BASELINE,
  CREWS,
  MAX_SHORT_EXPOSURE_RATIO,
  MARKET_OPEN_GRACE_PERIOD_MINUTES,
  LADDER_GAME_MAX_BALANCE,
  LADDER_GAME_MAX_DEPOSIT_PER_WINDOW,
  LADDER_DEPOSIT_WINDOW_MS,
  getCrewBuyTarget,
  getCrewSellTarget,
  getCrewVolumeTarget,
  SHORT_MARGIN_CALL_THRESHOLD,
  SHORT_MARGIN_DAMPENING_FACTOR,
  LONG_MARGIN_CALL_THRESHOLD,
  LONG_MARGIN_LIQUIDATION_THRESHOLD,
  IPO_PRICE_JUMP,
  IPO_SELL_LOCKUP_MS,
  MARGIN_SELL_LOCKUP_MS,
  EVENT_AMM_LIQUIDITY,
  EVENT_MIN_BUYIN,
  CREW_MEMBERS,
  ALL_CREW_TICKERS,
  ANIMAL_TICKERS,
  UNDERDOG_PRICE_THRESHOLD,
  FOURTEEN_DAYS_MS,
  ACTIVE_USER_WINDOW_MS,
  UNIFIER_FULL_SHARE_MIN,
  LADDER_GAME_INITIAL_BALANCE,
  LADDER_MIN_BET,
  LADDER_HIGH_BET_THRESHOLD,
  LADDER_ACHIEVEMENT_PROFIT,
  LADDER_ACHIEVEMENT_HIGH_BETS,
  LADDER_WITHDRAW_PRINCIPAL_FEE_RATE,
  LADDER_WITHDRAW_RUSH_RATE,
  LADDER_WITHDRAW_PROFIT_BRACKETS,
  WHALE_ALERT_SHARES_SOFT,
  WHALE_ALERT_PRICE_SOFT,
  WHALE_ALERT_SHARES_HARD,
  CREW_MILESTONE_THRESHOLDS,
  REINSTATE_CASH_DEFAULT,
  CREW_MISSION_REWARDS,
  CREW_CONTRIB,
  ADMIN_UID,
  DISCORD_DAILY_DROP_CHANNEL,
  DAILY_DROP_JACKPOT_CHANCE,
  DAILY_DROP_HIGH_TIER_FRACTION,
  DAILY_DROP_HIGH_TIER_CAP,
  DAILY_DROP_NORMAL_SHARE_VALUES,
  DAILY_DROP_NORMAL_SHARE_WEIGHTS,
  DAILY_DROP_NORMAL_VARIETY_VALUES,
  DAILY_DROP_NORMAL_VARIETY_WEIGHTS,
  DAILY_DROP_JACKPOT_SHARES_MIN,
  DAILY_DROP_JACKPOT_SHARES_MAX,
  DAILY_DROP_JACKPOT_VARIETY_MIN,
  DAILY_DROP_JACKPOT_VARIETY_MAX,
  COSMETIC_CATALOG,
  MAX_FN_INSTANCES,
  APP_CHECK_ENFORCED,
};
