// Shared constants for all Cloud Functions.
// Source of truth for economy rules — keep in sync with src/constants/economy.js.

// Crew rosters and mission economy values come from the synced copy of
// src/crews.js (functions/crews.js is generated by `npm run sync:chars`).
const {
  CREWS, CREW_MISSION_REWARDS, CREW_CONTRIB,
  getCrewBuyTarget, getCrewSellTarget, getCrewVolumeTarget,
  CREW_UNDERDOG_MULT_MAX, CREW_REJOIN_LOCKOUT_DAYS, CREW_SWITCH_PENALTY,
  CREW_SWITCH_EVENT, isFreeSwitchTarget,
} = require('./crews');

// ============================================
// MARKET MECHANICS
// ============================================
const BASE_IMPACT = 0.012;
const BASE_LIQUIDITY = 100;
const BID_ASK_SPREAD = 0.002;
const ETF_BID_ASK_SPREAD = 0.001;
const MIN_PRICE = 0.01;
const DUST_MAX_VALUE = 5; // positions worth less than this ($) are sweepable dust
const MAX_PRICE_CHANGE_PERCENT = 0.05;

// Anti-manipulation: per-user, per-ticker, per-day limits
const MAX_DAILY_IMPACT = 0.10;          // 10% max cumulative price move
const MAX_TRADES_PER_TICKER_24H = 10;   // Max buys or sells per ticker per rolling 24h

// How many limit orders on the same ticker one sweep may fill. Anything over
// the cap waits for the next 2-minute cycle, so a cluster of orders at the same
// price can't walk the price in a single run.
const ORDERS_PER_TICKER_PER_CYCLE = 3;

// Consecutive days holding an ETF to earn the Dividend Demon achievement.
const DIVIDEND_DEMON_HOLD_MS = 50 * 24 * 60 * 60 * 1000;

// Cooldown between display-name changes.
const NAME_CHANGE_COOLDOWN_MS = 14 * 24 * 60 * 60 * 1000;

// Admin price protection: after an admin manually sets a price, automated
// price movers (bot trader, market maker) leave that ticker alone for this
// long so they can't claw the adjustment back. Resets each time admin re-sets.
const ADMIN_PRICE_PROTECTION_MS = 7 * 24 * 60 * 60 * 1000; // 7 days

// Anti-manipulation: reduced price impact for brand-new accounts.
// Mirrors src/constants/economy.js — keep both in sync.
const NEW_ACCOUNT_IMPACT_PERIOD_DAYS = 3;  // ramps over the first 3 days
const NEW_ACCOUNT_MIN_IMPACT_FACTOR = 0.1; // 10% impact at day 0 → 100% at day 3

// Anti-alt: hard cap on accounts per IP, enforced at signup AND trade.
// ADMIN_UID is always exempt. Flip IP_ACCOUNT_CAP_ENABLED to false to disable the
// hard block instantly (e.g. if client IPs turn out unreliable) without a code change.
const MAX_ACCOUNTS_PER_IP = 2;
const IP_ACCOUNT_CAP_ENABLED = true;
// A deleted account keeps holding its per-IP slot for this long, then the slot
// frees up. Stops the pump → delete → remake loop (a month's wait per cycle makes
// it worthless) while still letting genuine deleters rejoin later.
const IP_SLOT_RELEASE_MS = 30 * 24 * 60 * 60 * 1000; // 30 days
// A Discord account linked to a now-deleted Stockism account is blocked from
// linking or creating a new one for this long. Mirrors IP_SLOT_RELEASE_MS: it
// kills the create → grab the verified $3k starting cash → gamble → delete →
// remake loop (and one aged Discord spawning troll accounts) by making each cycle
// cost a month's wait. The $3k bonus is one-time per live account, so within this
// window it can never be re-granted either.
const DISCORD_RELINK_COOLDOWN_MS = 30 * 24 * 60 * 60 * 1000; // 30 days

// How long a Discord-link handoff code stays valid. It is minted for the
// signed-in user by startDiscordLink and burned by discordLink, so it only has
// to outlive one trip through Discord's authorize screen.
const DISCORD_LINK_NONCE_TTL_MS = 10 * 60 * 1000; // 10 minutes

const TWENTY_FOUR_HOURS_MS = 24 * 60 * 60 * 1000;
const ONE_WEEK_MS           = 7 * 24 * 60 * 60 * 1000;
const THIRTY_DAYS_MS        = 30 * 24 * 60 * 60 * 1000;
const NINETY_DAYS_MS        = 90 * 24 * 60 * 60 * 1000;

// Read cap for the public-profile sparkline query (keeps per-view Firestore
// reads bounded no matter how many history points an account has).
const PUBLIC_PROFILE_SPARKLINE_MAX_POINTS = 150;

// ============================================
// WEEKLY TRADING HALT (Thursday 13:00–21:00 UTC)
// ============================================
const WEEKLY_HALT_START_MINUTE = 780;  // 13 * 60
const WEEKLY_HALT_END_MINUTE   = 1260; // 21 * 60
const PRE_MARKET_START_MINUTE  = 1230; // 20:30 UTC
const PRE_MARKET_LOCK_MINUTE   = 1255; // 20:55 UTC — no placements or cancellations after this; auction settles 20:56
// Max-buy headroom for pre-market orders: opening ask can sit up to ~5%
// (auction impact cap) + spread above the queue-time price, so placement
// validates against price * this buffer. Keep in sync with src/constants/economy.js.
const PRE_MARKET_MAX_BUY_BUFFER = 1.06;
// A single ticker's total short value (existing + new) can't exceed this
// fraction of portfolio equity.
const SHORT_CONCENTRATION_CAP = 0.5;

const isWeeklyTradingHalt = () => {
  const now = new Date();
  if (now.getUTCDay() !== 4) return false;
  const utcMins = now.getUTCHours() * 60 + now.getUTCMinutes();
  return utcMins >= WEEKLY_HALT_START_MINUTE && utcMins < WEEKLY_HALT_END_MINUTE;
};

// Shared by every side-game that closes with the market (event shares, weekly
// bets, IPO shares). One string so the halt never explains itself two ways.
const CHAPTER_REVIEW_HALT_MSG = 'Market closed for chapter review. Trading resumes at 21:00 UTC.';

// ============================================
// ECONOMY
// ============================================
const STARTING_CASH = 3000;            // full starting cash once verified (Discord linked)
const UNVERIFIED_STARTING_CASH = 1000; // starting cash before Discord verification (anti-alt)
const BAILOUT_CASH = 1500;
const NAME_CHANGE_COST = 10000;        // cash cost to change display name (changeDisplayName)

// Anti-manipulation: cooldown between buy/short on the same ticker by one user.
const TICKER_COOLDOWN_MS = 10000;      // 10 seconds

// Anti-manipulation: executeTrade throttle windows.
const TRADE_COOLDOWN_MS = 3000;               // min gap between any two trades by one user
const TRADE_HOLD_PERIOD_MS = 45 * 1000;       // min hold before a position can be sold/covered
const MAX_TRADES_PER_TICKER_HOUR = 15;        // buy/short velocity cap per ticker per hour
const TRADE_BURST_LIMIT = 3;                  // max buys or shorts per ticker per burst window
const TRADE_BURST_WINDOW_MS = 5 * 60 * 1000;  // 5 minutes
// After this many shorts on one ticker inside the rolling window, further
// shorts must wait for the oldest one to age out.
const MAX_SHORTS_BEFORE_COOLDOWN = 3;
const SHORT_COOLDOWN_WINDOW_MS = 8 * 60 * 60 * 1000; // 8 hours

// Daily check-in streak rewards. Index 0 = day 1. The reward escalates with the
// consecutive-day check-in streak, then caps at the last value forever (as long
// as the streak isn't broken). The streak itself is already tracked as
// checkinStreak. Day 1 stays at the old flat $300, so the curve is strictly an
// upgrade for everyone. Keep in sync with src/constants/economy.js.
const CHECKIN_STREAK_REWARDS = [300, 325, 350, 375, 400, 425, 500];
const SHORT_MARGIN_RATIO = 1.0; // 100% collateral — deposit dollar-for-dollar
const LEADERBOARD_CACHE_TTL = 5 * 60 * 1000; // 5 min — freshness window for the in-memory cache AND the shared leaderboard/{key} doc (keep in sync with LEADERBOARD_DOC_FRESH_MS in src/constants/economy.js)

// ============================================
// MARGIN
// ============================================
const MARGIN_INTEREST_RATE = 0.005;  // 0.5% per day
const MARGIN_CASH_MINIMUM  = 2000;   // min cash to enable margin — keep in sync with src/constants/economy.js

// Experience gates for enabling margin. The app has always shown these three as
// a requirements checklist and hidden the enable button until they were met,
// but only the client enforced them: toggleMargin checked cash alone, so a
// direct callable invocation got margin without any of them.
//
// Safe to enforce retroactively because all three metrics are monotonic — they
// only ever go up — so anyone who qualified once still qualifies, and nobody
// with margin already enabled can be locked out by toggling it off and back on.
// Keep in sync with src/constants/economy.js.
const MARGIN_MIN_CHECKINS       = 10;
const MARGIN_MIN_TRADES         = 35;
const MARGIN_MIN_PEAK_PORTFOLIO = 7500;
// CREW_SWITCH_PENALTY comes from crews.js (single source shared with the frontend)
const CREW_REJOIN_LOCKOUT_MS = CREW_REJOIN_LOCKOUT_DAYS * TWENTY_FOUR_HOURS_MS; // rejoin lockout after leaving a crew (from crews.js)
const MAX_SHORT_EXPOSURE_RATIO = 1.0; // total short value ≤ net worth (1:1 cap)
const MARKET_OPEN_GRACE_PERIOD_MINUTES = 30; // pause auto-liquidations after halt end
const LADDER_GAME_MAX_BALANCE = 10000; // max cash held in ladder minigame at once
const LADDER_GAME_MAX_DEPOSIT_PER_WINDOW = 10000; // max cash deposited into ladder within the rolling window
const LADDER_DEPOSIT_WINDOW_MS = 12 * 60 * 60 * 1000; // rolling 12h window for the deposit cap
// Crew buy/sell/volume goals scale with roster size (see getCrew*Target in crews.js)

// ============================================
// MARGIN THRESHOLDS
// ============================================
const SHORT_MARGIN_CALL_THRESHOLD    = 0.25; // short equity ratio below which force-cover triggers
const SHORT_MARGIN_DAMPENING_FACTOR  = 0.50; // reduced price impact for forced short covers
const LONG_MARGIN_CALL_THRESHOLD     = 0.30; // long margin equity ratio at which margin call is issued
const LONG_MARGIN_LIQUIDATION_THRESHOLD = 0.25; // long margin equity ratio at which auto-liquidation triggers

// Collateral rate to assume for a short position whose stored `margin` field is
// missing or zero (old or repaired docs). Current shorts are 100% collateral, so
// the fallback must match SHORT_MARGIN_RATIO — assuming less understates equity
// and force-covers a position that is actually healthy. Pre-v2 shorts really
// were half-collateral, so those keep the old rate. Keep in sync with
// src/constants/economy.js.
const LEGACY_SHORT_MARGIN_RATIO = 0.5;

// Price a forced long-margin liquidation sells at: 5% below market. The seller is
// dumping an entire portfolio at once and does not get to shop for a better fill.
const MARGIN_LIQUIDATION_SLIPPAGE = 0.05;

// Cap on forced short covers per ticker per run of checkShortMarginCalls, so one
// crowded short cannot cascade into a spike inside a single cycle.
//
// This is a BLAST-RADIUS cap, not a throughput setting. Each forced cover pushes
// the price up by at most MAX_PRICE_CHANGE_PERCENT (5%), and covers inside a run
// compound, so 3 is roughly a 16% worst-case move per ticker per run. Raising it
// to keep the old hourly liquidation rate after the schedule moved from 5 to 30
// minutes would allow ~140% in one burst — the squeeze the cap exists to stop.
//
// Consequence to know: at a 30-minute schedule a crowded underwater short drains
// ~6x slower than when this was written. That is the safe direction to be wrong
// in, but if liquidation latency ever becomes the problem, fix it by running the
// scan more often, NOT by raising this number.
const SHORT_MARGIN_CALL_INTERVAL_MINUTES = 30;
const FORCED_COVERS_PER_TICKER_PER_CYCLE = 3;

// Firestore caps a batched write at 500 ops; stay under it with room to spare.
const FIRESTORE_BATCH_SIZE = 400;

// ============================================
// IPO
// ============================================
const IPO_PRICE_JUMP = 0.15; // 15% price bump when IPO fully subscribed
// IPO-bought shares are locked from selling until ipoEndsAt + this buffer, so the
// guaranteed +15% launch pop can't be flipped for a risk-free profit. Measured
// from ipoEndsAt because shares already can't trade before launch: a last-second
// buyer (who triggers an early sellout) still has to hold through the float window,
// and an early buyer holds through the IPO they opted into.
const IPO_SELL_LOCKUP_MS = 24 * 60 * 60 * 1000; // 24 hours
// Shares bought with margin are locked from re-selling this long, so borrowed
// money can't be used to spike a stock and bail before the price reverts.
const MARGIN_SELL_LOCKUP_MS = 36 * 60 * 60 * 1000; // 36 hours

// ============================================
// EVENT PREDICTION MARKETS (long-term, AMM-priced)
// ============================================
// LMSR liquidity parameter (b). Bigger = steadier prices and a larger bounded
// house subsidy. Max the house can ever lose on a market is b * ln(numOutcomes)
// (~$3,466 for a yes/no market at b=5000). Seeded generously on purpose: stable
// prices and generous payouts build trust, and a deep book stops one big early
// bet from yanking the line.
const EVENT_AMM_LIQUIDITY = 5000;
const EVENT_MIN_BUYIN = 1; // minimum dollar cost of a single buy (avoids dust)

// ============================================
// CREW MEMBER MAPPINGS
// ============================================
// Derived from src/crews.js via the synced functions/crews.js — never list
// rosters here by hand (a hand-copied list once drifted and broke missions
// for newly added characters).
const CREW_MEMBERS = {};
Object.values(CREWS).forEach((c) => { CREW_MEMBERS[c.id] = c.members; });

const ALL_CREW_TICKERS = new Set(Object.values(CREW_MEMBERS).flat());

const ANIMAL_TICKERS = new Set(['RYAN', 'EDEN', 'MIRO', 'ENU']);

// Buys below this price count for the Underdog Investor daily mission.
const UNDERDOG_PRICE_THRESHOLD = 20;

// ============================================
// LEADERBOARD
// ============================================
const FOURTEEN_DAYS_MS = 14 * 24 * 60 * 60 * 1000;
// A user counts as "active" if they opened the app or did anything in this
// window.
const ACTIVE_USER_WINDOW_MS = FOURTEEN_DAYS_MS;
const ACTIVE_USER_WINDOW_DAYS = Math.round(ACTIVE_USER_WINDOW_MS / (24 * 60 * 60 * 1000));

// transactionLog entry types that count as a trade. Shorts belong here: leaving
// them out undercounted both trade totals and the number of people trading.
const TRADE_TX_TYPES = new Set(['BUY', 'SELL', 'SHORT_OPEN', 'SHORT_CLOSE']);

// `action` values in the trades collection that count as a player trade. That
// collection also holds dividend payouts and forced margin closes, which are
// not trades anyone placed.
const TRADE_RECORD_ACTIONS = new Set(['buy', 'sell', 'short', 'cover']);

// ============================================
// ACHIEVEMENTS
// ============================================
// Unifier of Seoul: a character only counts toward the achievement if the user
// holds at least one FULL share. The threshold sits just under 1.0 to tolerate
// floating-point dust from fractional trades (e.g. 0.3333 + 0.6667 landing on
// 0.9999999999999999) while still rejecting any genuine partial holding.
const UNIFIER_FULL_SHARE_MIN = 0.999999;

// ============================================
// LADDER GAME
// ============================================
const LADDER_GAME_INITIAL_BALANCE    = 500;   // starting balance for new ladder game users
const LADDER_MIN_BET                 = 1;     // ladder bets are whole dollars only; decimals are floored away (no decimals = no rounding exploit)
const LADDER_HIGH_BET_THRESHOLD      = 50;    // bets at or above this count toward ADDICTED achievement
const LADDER_ACHIEVEMENT_PROFIT      = 2500;  // net profit needed for COMPULSIVE_GAMBLER achievement
const LADDER_ACHIEVEMENT_HIGH_BETS   = 100;   // high-bet games needed for ADDICTED achievement

// Withdrawal tax — keep in sync with src/constants/economy.js
const LADDER_WITHDRAW_PRINCIPAL_FEE_RATE = 0.05; // flat 5% on the portion that is deposited principal coming back
const LADDER_WITHDRAW_RUSH_RATE          = 0.15; // +15% of the whole withdrawal if any deposit landed within LADDER_DEPOSIT_WINDOW_MS
// Lifetime-progressive brackets over cumulative profit withdrawn (not per-withdrawal,
// so splitting withdrawals can't dodge a bracket). upTo = upper bound of cumulative
// profit withdrawn that the rate applies to.
const LADDER_WITHDRAW_PROFIT_BRACKETS = [
  { upTo: 1000,     rate: 0.15 },
  { upTo: 5000,     rate: 0.30 },
  { upTo: Infinity, rate: 0.45 },
];

// ============================================
// DISCORD ALERTS
// ============================================
const WHALE_ALERT_SHARES_SOFT   = 50;   // shares threshold (combined with price check) for whale alert
const WHALE_ALERT_PRICE_SOFT    = 35;   // price threshold (combined with shares check) for whale alert
const WHALE_ALERT_SHARES_HARD   = 100;  // shares threshold alone triggers whale alert regardless of price
const CREW_MILESTONE_THRESHOLDS = [5, 10, 25, 50, 100]; // crew member counts that trigger Discord alerts

// ============================================
// ADMIN OPS
// ============================================
const REINSTATE_CASH_DEFAULT = 1000; // cash given when admin reinstates a bankrupt user

// ============================================
// MISSION REWARDS
// ============================================
// Daily/weekly mission payouts live on the mission definitions in crews.js
// (claimMissionReward reads them off the assigned mission). Crew mission
// values are re-exported from crews.js below so services keep importing
// everything from this hub.

// ============================================
// ADMIN
// ============================================
// Set via functions/.env in production; fallback for local dev only.
// This is the admin account's Firebase UID — every admin-only function checks against it.
const ADMIN_UID = process.env.ADMIN_UID || '4usiVxPmHLhmitEKH2HfCpbx4Yi1';

// ============================================
// DISCORD CHANNELS
// ============================================
// Channel the daily free-stock drop posts to. Used by discord.js (dailyFreeStock) and
// health.js (discordHealthCheck) — single source of truth so the two can't drift.
const DISCORD_DAILY_DROP_CHANNEL = '1483767343581761658';

// ============================================
// DISCORD CREW HEAD ROLES (discordRoles.js)
// ============================================
// Every Monday the weekly crew rankings crown a head per crew. These roles
// make that visible in Discord: the head wears their crew's role, which colors
// their name (and shows the crew icon beside it if the server is Boost Level
// 2 — colors work at any level, icons silently don't below 2).
//
// The bot NEVER creates or edits roles. The roles are made by hand in Discord
// with whatever name/color/icon we want; the bot only adds and removes
// assignments, so its permission stays at Manage Roles alone. Its own role
// must sit ABOVE these in the hierarchy or Discord rejects every call with 403.
//
// Guild and role IDs live here rather than .env because they are not secrets
// (every server member can see them) and a mistyped ID is invisible forever in
// a gitignored file but obvious in a diff. The bot TOKEN stays in .env.
//
// A blank role ID disables that crew entirely — no add, no remove. All blank
// (the default) no-ops the whole feature, so this ships safely before the
// Discord side is set up.
const DISCORD_GUILD_ID = process.env.DISCORD_GUILD_ID || '';
const CREW_HEAD_ROLE_IDS = {
  ALLIED: '',
  BIG_DEAL: '',
  FIST_GANG: '',
  GOD_DOG: '',
  SECRET_FRIENDS: '',
  HOSTEL: '',
  WTJC: '',
  WORKERS: '',
  YAMAZAKI: '',
  KITAE_UNION: '',
};
// Discord snowflakes are 17-20 digits. Catches a truncated paste, the single
// likeliest setup mistake.
const DISCORD_SNOWFLAKE_PATTERN = /^\d{17,20}$/;
const DISCORD_API_TIMEOUT_MS = 10000;        // per request
const DISCORD_ROLE_CALL_SPACING_MS = 300;    // polite gap between role writes
const DISCORD_ROLE_SYNC_BUDGET_MS = 25000;   // whole-sync wall clock ceiling
const DISCORD_ROLE_RETRY_MAX_MS = 5000;      // longest 429 retry_after we wait out

// ============================================
// DISCORD SLASH COMMANDS (discordCommands.js)
// ============================================
// The bot is installable in partner servers, so command traffic comes from
// people we don't control. Per-user cooldown keeps a spam loop in one server
// from burning the Firestore free tier. Held in instance memory only — a cold
// start clears it, which is fine because the cap exists to blunt sustained
// spam, not to be an exact quota.
const DISCORD_COMMAND_COOLDOWN_MS = 3 * 1000;
// How long a warm instance will wait for a command's reads before giving up and
// deferring instead. Discord hard-kills any interaction not acknowledged within
// 3s, so this must leave comfortable room for the response to travel back.
const DIRECT_REPLY_BUDGET_MS = 1200;
// Public site URL. Slash-command replies deep-link back here (this is the whole
// point of the "trade on the website" buttons).
const SITE_URL = 'https://stockism.app';
// How many leaderboard rows a /leaderboard reply shows. Discord embeds get
// unreadable past ~10 lines on mobile.
const DISCORD_LEADERBOARD_ROWS = 10;
// How many holdings a /portfolio reply shows before it summarises the rest.
const DISCORD_PORTFOLIO_ROWS = 8;

// ============================================
// DISCORD DAILY DROP (loot roll in dailyDropRoll.js)
// ============================================
// A normal claim draws from THREE tables. The roster has grown a long cheap
// tail (over a third of it trades under $25), and when one flat pool fed the
// whole roll most days paid out a single share of a $10 character. So the
// cheap end now rides on top of the real pull instead of replacing it:
//
//   CORE table       the actual pull, drawn from the mid tiers. Always pays.
//   BONUS table      cheapest tiers, several shares. Always pays.
//   LEGENDARY table  a slim chance at ONE legendary share. Usually pays nothing.
//   JACKPOT          3% of claims, replaces the core pull with a legendary haul
//
// Tiers come from computeRarityTiers (src/characters.js), which ranks by LIVE
// price rather than basePrice and re-sorts itself as the market moves. New
// cheap characters therefore route themselves into the bonus table with no
// maintenance here.
//
// Legendary is deliberately absent from the CORE table — a single legendary
// share outvalues a whole good roll, so making it a routine core outcome would
// wreck the predictable everyday payout. The legendary table is how it stays
// reachable anyway: rare, one share, and capped to the cheaper half of the
// tier so the priciest legendaries remain jackpot-exclusive.
//
// Calibrated against live prices 2026-07-31: mean $425/claim, typical $296,
// worst 10% of claims still clear $181. Re-run scripts/sim-daily-drop.cjs
// after changing any weight below.
const DAILY_DROP_JACKPOT_CHANCE = 0.03;            // 3% of claims are jackpots

// Bonus table — the cheap end of the roster, added to every single claim.
const DAILY_DROP_BONUS_TIERS = ['common', 'uncommon'];
const DAILY_DROP_BONUS_SHARE_VALUES = [3, 4, 5, 6, 7];
const DAILY_DROP_BONUS_SHARE_WEIGHTS = [20, 30, 25, 17, 8];
const DAILY_DROP_BONUS_VARIETY_VALUES = [1, 2, 3];   // how many different stocks
const DAILY_DROP_BONUS_VARIETY_WEIGHTS = [30, 45, 25];

// Core table — the main pull. Share counts are per-tier so an epic pull can't
// hand out as many shares as a rare one.
const DAILY_DROP_CORE_TIER_VALUES = ['rare', 'epic'];
const DAILY_DROP_CORE_TIER_WEIGHTS = [55, 45];
const DAILY_DROP_CORE_SHARE_VALUES = { rare: [2, 3, 4], epic: [1, 2, 3] };
const DAILY_DROP_CORE_SHARE_WEIGHTS = { rare: [35, 40, 25], epic: [35, 45, 20] };
const DAILY_DROP_CORE_VARIETY_VALUES = [1, 2];
const DAILY_DROP_CORE_VARIETY_WEIGHTS = [70, 30];

// Legendary table — the third roll on a normal claim, and usually a miss.
// Pays ONE share, drawn from the cheapest slice of the legendary tier, so it
// reads as a lucky bonus rather than a stealth jackpot. On live prices that
// slice is the four legendaries around $350-$400; the $970+ megacaps sit above
// the cut and stay jackpot-only.
const DAILY_DROP_LEGENDARY_CHANCE = 0.10;          // ~1 in 10 normal rolls
const DAILY_DROP_LEGENDARY_SHARES = 1;
const DAILY_DROP_LEGENDARY_POOL_FRACTION = 0.5;    // cheapest half of the tier

// Jackpot — draws the whole legendary tier, megacaps included.
const DAILY_DROP_JACKPOT_TIERS = ['legendary', 'epic'];
const DAILY_DROP_JACKPOT_SHARES_MIN = 6;
const DAILY_DROP_JACKPOT_SHARES_MAX = 10;
const DAILY_DROP_JACKPOT_VARIETY_MIN = 3;
const DAILY_DROP_JACKPOT_VARIETY_MAX = 5;

// ============================================
// CLOUD FUNCTION SAFETY CAPS (cost / abuse blast radius)
// ============================================
// Cosmetic catalog — validates shop purchases (purchaseCosmetic) and admin
// grants (adminGrantCosmetic). Keep ids/prices in sync with the frontend list
// in src/constants/cosmetics.js.
const COSMETIC_CATALOG = {
  name_gold:         { type: 'nameColor',   price: 5000  },
  name_crimson:      { type: 'nameColor',   price: 5000  },
  name_emerald:      { type: 'nameColor',   price: 5000  },
  name_sapphire:     { type: 'nameColor',   price: 5000  },
  name_violet:       { type: 'nameColor',   price: 5000  },
  name_rose:         { type: 'nameColor',   price: 5000  },
  name_cyan:         { type: 'nameColor',   price: 5000  },
  name_silver:       { type: 'nameColor',   price: 5000  },
  name_tangerine:    { type: 'nameColor',   price: 5000  },
  glow_gold:         { type: 'rowGlow',     price: 15000 },
  glow_crimson:      { type: 'rowGlow',     price: 15000 },
  glow_neon:         { type: 'rowGlow',     price: 15000 },
  glow_pink:         { type: 'rowGlow',     price: 15000 },
  glow_sapphire:     { type: 'rowGlow',     price: 15000 },
  glow_violet:       { type: 'rowGlow',     price: 15000 },
  glow_cyan:         { type: 'rowGlow',     price: 15000 },
  glow_orange:       { type: 'rowGlow',     price: 15000 },
  glow_silver:       { type: 'rowGlow',     price: 15000 },
  backdrop_royal:    { type: 'rowBackdrop', price: 25000 },
  backdrop_inferno:  { type: 'rowBackdrop', price: 25000 },
  backdrop_frost:    { type: 'rowBackdrop', price: 25000 },
  backdrop_blush:    { type: 'rowBackdrop', price: 25000 },
  backdrop_verdant:  { type: 'rowBackdrop', price: 25000 },
  backdrop_gilded:   { type: 'rowBackdrop', price: 25000 },
  backdrop_midnight: { type: 'rowBackdrop', price: 25000 },
  backdrop_onyx:     { type: 'rowBackdrop', price: 25000 },
  backdrop_lagoon:   { type: 'rowBackdrop', price: 25000 },
  // Animated cosmetics
  name_shimmer:       { type: 'nameColor',   price: 40000  },
  name_aurora:        { type: 'nameColor',   price: 50000  },
  name_rainbow:       { type: 'nameColor',   price: 60000  },
  frame_ember:        { type: 'rowFrame',    price: 80000  },
  frame_frost:        { type: 'rowFrame',    price: 80000  },
  frame_electric:     { type: 'rowFrame',    price: 90000  },
  frame_gold:         { type: 'rowFrame',    price: 120000 },
  glow_pulse_gold:     { type: 'rowGlow',    price: 50000  },
  glow_pulse_crimson:  { type: 'rowGlow',    price: 50000  },
  glow_pulse_neon:     { type: 'rowGlow',    price: 50000  },
  glow_pulse_pink:     { type: 'rowGlow',    price: 50000  },
  glow_pulse_sapphire: { type: 'rowGlow',    price: 50000  },
  glow_pulse_violet:   { type: 'rowGlow',    price: 50000  },
  glow_pulse_cyan:     { type: 'rowGlow',    price: 50000  },
  glow_pulse_orange:   { type: 'rowGlow',    price: 50000  },
  glow_pulse_silver:   { type: 'rowGlow',    price: 50000  },
};

// Crew head ("top dog") — assigned automatically every Monday by
// weeklyCrewRankings: the biggest PORTFOLIO among a crew's active members.
// It used to be best weekly percentage gain, which players found confusing —
// a small account having one good week outranked the crew's actual
// heavyweight, and the crown changed hands for reasons nobody could see.
// Wealth is the obvious reading of "crew head", so that is what it is now.
// The crown carries no payout, only cosmetics, so ranking by size hands
// whales no economic advantage.
// Dynasty weeks = the streak that earns DYNASTY, and the reign length that
// makes dethroning someone count as USURPER.
const CREW_HEAD_DYNASTY_WEEKS = 4;

// Minimum 7-day-ago portfolio value to appear on the percent-gain leaderboard:
// a $50 account doubling up must not outrank real portfolios with a
// meaningless percentage.
const LEADERBOARD_PERCENT_MIN_BASELINE = 1000;

// Max LIVE price-history points kept per ticker in market/priceHistory. The
// limit that matters is Firestore's ~40k index entries PER DOCUMENT, shared by
// all ~150 tickers: at ~20k total points the doc rejected every append and
// trades failed ("too many index entries", 2026-07-22 incident). 60/ticker
// bounds the doc to ~9k points worst case. Older points are ARCHIVED (moved,
// never deleted) to market/current/price_history/{ticker}; charts merge the
// archive back in, so trimming costs nothing visible.
const PRICE_HISTORY_LIVE_MAX = 60;

// Hard ceiling on how many copies of any one function can run at the same time.
// Bounds how fast cost can pile up if a function is flooded (deliberate abuse or a
// bug) without affecting normal play. Lower = safer on cost; too low could throttle
// trades at a busy market open. Applied to every function via functions/fnConfig.js.
const MAX_FN_INSTANCES = 10;

// App Check enforcement on callable functions. When true, callables reject any
// request that didn't come from our real app (no valid App Check token), which
// blocks outside scripts from hammering the backend. OFF by default on purpose:
// turn it on ONLY after confirming in Firebase Console → App Check that real
// traffic is ~100% verified, or legitimate players could be locked out. Flip back
// to false to disable instantly without a code change (mirrors IP_ACCOUNT_CAP_ENABLED).
const APP_CHECK_ENFORCED = false;

module.exports = {
  BASE_IMPACT,
  BASE_LIQUIDITY,
  BID_ASK_SPREAD,
  ETF_BID_ASK_SPREAD,
  MIN_PRICE,
  DUST_MAX_VALUE,
  MAX_PRICE_CHANGE_PERCENT,
  MAX_DAILY_IMPACT,
  MAX_TRADES_PER_TICKER_24H,
  ORDERS_PER_TICKER_PER_CYCLE,
  DIVIDEND_DEMON_HOLD_MS,
  NAME_CHANGE_COOLDOWN_MS,
  ADMIN_PRICE_PROTECTION_MS,
  NEW_ACCOUNT_IMPACT_PERIOD_DAYS,
  NEW_ACCOUNT_MIN_IMPACT_FACTOR,
  MAX_ACCOUNTS_PER_IP,
  IP_ACCOUNT_CAP_ENABLED,
  IP_SLOT_RELEASE_MS,
  DISCORD_RELINK_COOLDOWN_MS,
  DISCORD_LINK_NONCE_TTL_MS,
  TWENTY_FOUR_HOURS_MS,
  ONE_WEEK_MS,
  THIRTY_DAYS_MS,
  PUBLIC_PROFILE_SPARKLINE_MAX_POINTS,
  NINETY_DAYS_MS,
  SHORT_MARGIN_RATIO,
  WEEKLY_HALT_START_MINUTE,
  WEEKLY_HALT_END_MINUTE,
  PRE_MARKET_START_MINUTE,
  PRE_MARKET_LOCK_MINUTE,
  PRE_MARKET_MAX_BUY_BUFFER,
  SHORT_CONCENTRATION_CAP,
  isWeeklyTradingHalt,
  CHAPTER_REVIEW_HALT_MSG,
  STARTING_CASH,
  UNVERIFIED_STARTING_CASH,
  BAILOUT_CASH,
  NAME_CHANGE_COST,
  TICKER_COOLDOWN_MS,
  TRADE_COOLDOWN_MS,
  TRADE_HOLD_PERIOD_MS,
  MAX_TRADES_PER_TICKER_HOUR,
  TRADE_BURST_LIMIT,
  TRADE_BURST_WINDOW_MS,
  MAX_SHORTS_BEFORE_COOLDOWN,
  SHORT_COOLDOWN_WINDOW_MS,
  CHECKIN_STREAK_REWARDS,
  LEADERBOARD_CACHE_TTL,
  MARGIN_INTEREST_RATE,
  MARGIN_CASH_MINIMUM,
  MARGIN_MIN_CHECKINS,
  MARGIN_MIN_TRADES,
  MARGIN_MIN_PEAK_PORTFOLIO,
  CREW_SWITCH_PENALTY,
  CREW_SWITCH_EVENT,
  isFreeSwitchTarget,
  CREW_REJOIN_LOCKOUT_MS,
  CREW_UNDERDOG_MULT_MAX,
  CREW_HEAD_DYNASTY_WEEKS,
  LEADERBOARD_PERCENT_MIN_BASELINE,
  PRICE_HISTORY_LIVE_MAX,
  CREWS,
  MAX_SHORT_EXPOSURE_RATIO,
  MARKET_OPEN_GRACE_PERIOD_MINUTES,
  LADDER_GAME_MAX_BALANCE,
  LADDER_GAME_MAX_DEPOSIT_PER_WINDOW,
  LADDER_DEPOSIT_WINDOW_MS,
  getCrewBuyTarget,
  getCrewSellTarget,
  getCrewVolumeTarget,
  SHORT_MARGIN_CALL_THRESHOLD,
  SHORT_MARGIN_DAMPENING_FACTOR,
  LONG_MARGIN_CALL_THRESHOLD,
  LONG_MARGIN_LIQUIDATION_THRESHOLD,
  LEGACY_SHORT_MARGIN_RATIO,
  MARGIN_LIQUIDATION_SLIPPAGE,
  SHORT_MARGIN_CALL_INTERVAL_MINUTES,
  FORCED_COVERS_PER_TICKER_PER_CYCLE,
  FIRESTORE_BATCH_SIZE,
  IPO_PRICE_JUMP,
  IPO_SELL_LOCKUP_MS,
  MARGIN_SELL_LOCKUP_MS,
  EVENT_AMM_LIQUIDITY,
  EVENT_MIN_BUYIN,
  CREW_MEMBERS,
  ALL_CREW_TICKERS,
  ANIMAL_TICKERS,
  UNDERDOG_PRICE_THRESHOLD,
  FOURTEEN_DAYS_MS,
  ACTIVE_USER_WINDOW_MS,
  ACTIVE_USER_WINDOW_DAYS,
  TRADE_TX_TYPES,
  TRADE_RECORD_ACTIONS,
  UNIFIER_FULL_SHARE_MIN,
  LADDER_GAME_INITIAL_BALANCE,
  LADDER_MIN_BET,
  LADDER_HIGH_BET_THRESHOLD,
  LADDER_ACHIEVEMENT_PROFIT,
  LADDER_ACHIEVEMENT_HIGH_BETS,
  LADDER_WITHDRAW_PRINCIPAL_FEE_RATE,
  LADDER_WITHDRAW_RUSH_RATE,
  LADDER_WITHDRAW_PROFIT_BRACKETS,
  WHALE_ALERT_SHARES_SOFT,
  WHALE_ALERT_PRICE_SOFT,
  WHALE_ALERT_SHARES_HARD,
  CREW_MILESTONE_THRESHOLDS,
  REINSTATE_CASH_DEFAULT,
  CREW_MISSION_REWARDS,
  CREW_CONTRIB,
  ADMIN_UID,
  DISCORD_DAILY_DROP_CHANNEL,
  DISCORD_GUILD_ID,
  CREW_HEAD_ROLE_IDS,
  DISCORD_SNOWFLAKE_PATTERN,
  DISCORD_API_TIMEOUT_MS,
  DISCORD_ROLE_CALL_SPACING_MS,
  DISCORD_ROLE_SYNC_BUDGET_MS,
  DISCORD_ROLE_RETRY_MAX_MS,
  DISCORD_COMMAND_COOLDOWN_MS,
  DIRECT_REPLY_BUDGET_MS,
  DISCORD_LEADERBOARD_ROWS,
  DISCORD_PORTFOLIO_ROWS,
  SITE_URL,
  DAILY_DROP_JACKPOT_CHANCE,
  DAILY_DROP_BONUS_TIERS,
  DAILY_DROP_BONUS_SHARE_VALUES,
  DAILY_DROP_BONUS_SHARE_WEIGHTS,
  DAILY_DROP_BONUS_VARIETY_VALUES,
  DAILY_DROP_BONUS_VARIETY_WEIGHTS,
  DAILY_DROP_CORE_TIER_VALUES,
  DAILY_DROP_CORE_TIER_WEIGHTS,
  DAILY_DROP_CORE_SHARE_VALUES,
  DAILY_DROP_CORE_SHARE_WEIGHTS,
  DAILY_DROP_CORE_VARIETY_VALUES,
  DAILY_DROP_CORE_VARIETY_WEIGHTS,
  DAILY_DROP_LEGENDARY_CHANCE,
  DAILY_DROP_LEGENDARY_SHARES,
  DAILY_DROP_LEGENDARY_POOL_FRACTION,
  DAILY_DROP_JACKPOT_TIERS,
  DAILY_DROP_JACKPOT_SHARES_MIN,
  DAILY_DROP_JACKPOT_SHARES_MAX,
  DAILY_DROP_JACKPOT_VARIETY_MIN,
  DAILY_DROP_JACKPOT_VARIETY_MAX,
  COSMETIC_CATALOG,
  MAX_FN_INSTANCES,
  APP_CHECK_ENFORCED,
};
