// One lint config for the whole repo: frontend (src/), backend (functions/), scripts.
// Focus: real bugs (hooks rules, undefined names) and the file-size limits from
// CLAUDE.md. Formatting is Prettier's job, not ESLint's.
import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import react from 'eslint-plugin-react';
import reactHooks from 'eslint-plugin-react-hooks';
import globals from 'globals';

// Line limits count code only (blank lines and comments are free).
const maxLines = (max, severity = 'error') => ({
  'max-lines': [severity, { max, skipBlankLines: true, skipComments: true }],
});

const unusedVars = {
  // `_` is the convention for intentionally-ignored params/destructure slots.
  argsIgnorePattern: '^_',
  varsIgnorePattern: '^_$',
  destructuredArrayIgnorePattern: '^_',
  caughtErrors: 'none',
};

export default tseslint.config(
  {
    ignores: [
      'dist',
      'coverage',
      'local',
      '**/node_modules',
      'functions/lib',
      // Generated by `npm run sync:chars` from src/.
      'functions/characters.js',
      'functions/crews.js',
    ],
  },

  // ---- Frontend ----
  {
    files: ['src/**/*.{js,jsx,ts,tsx}'],
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    plugins: { react, 'react-hooks': reactHooks },
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      parserOptions: { ecmaFeatures: { jsx: true } },
      globals: { ...globals.browser, __APP_VERSION__: 'readonly', __BUILD_TIME__: 'readonly' },
    },
    settings: { react: { version: 'detect' } },
    rules: {
      ...react.configs.recommended.rules,
      ...react.configs['jsx-runtime'].rules,
      'react/prop-types': 'off',
      'react/no-unescaped-entities': 'off',
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'warn',
      'no-unused-vars': 'off',
      '@typescript-eslint/no-unused-vars': ['warn', unusedVars],
      // Plain JS files are still being converted; don't demand TS syntax from them.
      '@typescript-eslint/no-require-imports': 'off',
      'no-empty': 'warn',
    },
  },
  { files: ['src/**/*.test.{js,jsx,ts,tsx}'], languageOptions: { globals: globals.node } },

  // File-size limits (CLAUDE.md). Split the file rather than raise these.
  { files: ['src/components/**/*.{js,jsx,ts,tsx}'], ignores: ['**/*.test.*'], rules: maxLines(400) },
  { files: ['src/pages/**/*.{js,jsx,ts,tsx}'], ignores: ['**/*.test.*'], rules: maxLines(300) },
  { files: ['src/hooks/**/*.{js,jsx,ts,tsx}'], ignores: ['**/*.test.*'], rules: maxLines(200) },
  { files: ['src/App.{jsx,tsx}'], rules: maxLines(500) },
  // Over their limit after the 2026-10 reformat. Warn-only until the frontend
  // restructure splits them (docs/MODERNIZATION.md). Remove entries as they're split.
  {
    files: [
      'src/App.{jsx,tsx}',
      'src/pages/StockPage.{jsx,tsx}',
    ],
    rules: { 'max-lines': 'warn' },
  },

  // ---- Backend (Cloud Functions, CommonJS) ----
  {
    files: ['functions/**/*.js'],
    languageOptions: { ecmaVersion: 2022, sourceType: 'commonjs', globals: globals.node },
    rules: { 'no-undef': 'error' },
  },
  { files: ['functions/**/*.test.js'], languageOptions: { sourceType: 'module' } },
  { files: ['functions/services/**/*.js'], rules: maxLines(600) },
  { files: ['functions/index.js'], rules: maxLines(15) },
);
