// One lint config for the whole repo: frontend (src/), backend (functions/), scripts.
// Focus: real bugs (hooks rules, undefined names) and the file-size limits from
// CLAUDE.md. Formatting is Prettier's job, not ESLint's.
import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import react from 'eslint-plugin-react';
import reactHooks from 'eslint-plugin-react-hooks';
import globals from 'globals';

// Line limits count code only (blank lines and comments are free).
const maxLines = (max, severity = 'error') => ({
  'max-lines': [severity, { max, skipBlankLines: true, skipComments: true }],
});

const unusedVars = {
  // `_` is the convention for intentionally-ignored params/destructure slots.
  argsIgnorePattern: '^_',
  varsIgnorePattern: '^_$',
  destructuredArrayIgnorePattern: '^_',
  caughtErrors: 'none',
};

export default tseslint.config(
  {
    ignores: [
      'dist',
      'coverage',
      'local',
      '**/node_modules',
      'functions/lib',
      // Generated by `npm run sync:chars` from src/.
      'functions/src/shared/characters.ts',
      'functions/src/shared/crews.ts',
      'functions/src/shared/rules/**',
    ],
  },

  // ---- Frontend ----
  {
    files: ['src/**/*.{ts,tsx}'],
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    plugins: { react, 'react-hooks': reactHooks },
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      parserOptions: { ecmaFeatures: { jsx: true } },
      globals: { ...globals.browser, __APP_VERSION__: 'readonly', __BUILD_TIME__: 'readonly' },
    },
    settings: { react: { version: 'detect' } },
    rules: {
      ...react.configs.recommended.rules,
      ...react.configs['jsx-runtime'].rules,
      'react/prop-types': 'off',
      'react/no-unescaped-entities': 'off',
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'warn',
      'no-unused-vars': 'off',
      '@typescript-eslint/no-unused-vars': ['warn', unusedVars],
      'no-empty': 'warn',
    },
  },
  { files: ['src/**/*.test.{ts,tsx}'], languageOptions: { globals: globals.node } },

  // File-size limits (CLAUDE.md). Split the file rather than raise these.
  {
    files: ['src/{features/*,shared}/components/**/*.{ts,tsx}', 'src/app/**/*.{ts,tsx}'],
    ignores: ['**/*.test.*'],
    rules: maxLines(400),
  },
  { files: ['src/features/*/pages/**/*.{ts,tsx}'], ignores: ['**/*.test.*'], rules: maxLines(300) },
  { files: ['src/{features/*,shared}/hooks/**/*.{ts,tsx}'], ignores: ['**/*.test.*'], rules: maxLines(200) },
  { files: ['src/App.tsx'], rules: maxLines(500) },

  // ---- Emulator suites (vitest; backend code comes in through createRequire) ----
  {
    files: ['tests/**/*.js'],
    extends: [js.configs.recommended],
    languageOptions: { ecmaVersion: 'latest', sourceType: 'module', globals: globals.node },
    rules: { 'no-unused-vars': ['warn', unusedVars] },
  },

  // ---- Backend (Cloud Functions; TypeScript compiled to CommonJS by tsc) ----
  {
    files: ['functions/{src,test}/**/*.ts'],
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    languageOptions: { ecmaVersion: 'latest', sourceType: 'module', globals: globals.node },
    rules: {
      'no-unused-vars': 'off',
      '@typescript-eslint/no-unused-vars': ['warn', unusedVars],
    },
  },
  {
    files: ['functions/src/**/*.ts'],
    ignores: ['**/*.test.*', 'functions/src/shared/**'],
    rules: maxLines(600),
  },
  { files: ['functions/src/index.ts'], rules: maxLines(15) },
);
