// All Lookism characters with their base stats
export const CHARACTERS = [
  { name: "James Lee", ticker: "DG", basePrice: 85, volatility: 0.03 },
  { name: "Shingen Yamazaki", ticker: "SHNG", basePrice: 85, volatility: 0.03 },
  { name: "Gapryong Kim", ticker: "GAP", basePrice: 85, volatility: 0.03 },
  { name: "Gun Park", ticker: "GUN", basePrice: 85, volatility: 0.035 },
  { name: "Goo Kim", ticker: "GOO", basePrice: 85, volatility: 0.035 },
  { name: "Sophia Alexander", ticker: "SOPH", basePrice: 80, volatility: 0.035 },
  { name: "Kitae Kim", ticker: "KTAE", basePrice: 80, volatility: 0.035 },
  { name: "Daniel Park (Big)", ticker: "BDNL", basePrice: 80, volatility: 0.04 },
  { name: "Tom Lee", ticker: "TOM", basePrice: 78, volatility: 0.035 },
  { name: "Shintaro Yamazaki", ticker: "SHRO", basePrice: 75, volatility: 0.035 },
  { name: "Manager Kim", ticker: "SRMK", basePrice: 74, volatility: 0.03 },
  { name: "Charles Choi", ticker: "ELIT", basePrice: 72, volatility: 0.025 },
  { name: "Jinyeong Park", ticker: "JYNG", basePrice: 72, volatility: 0.03 },
  { name: "Johan Seong", ticker: "GDOG", basePrice: 80, volatility: 0.045 },
  { name: "Paecheon Jo", ticker: "CROC", basePrice: 60, volatility: 0.03 },
  { name: "Jake Kim", ticker: "JAKE", basePrice: 73, volatility: 0.04 },
  { name: "Taesoo Ma", ticker: "TM", basePrice: 60, volatility: 0.035 },
  { name: "Eli Jang", ticker: "ELI", basePrice: 60, volatility: 0.04 },
  { name: "Samuel Seo", ticker: "SAM", basePrice: 58, volatility: 0.04 },
  { name: "Jaegyeon Na", ticker: "JAEG", basePrice: 62, volatility: 0.035 },
  { name: "Yujae Seon", ticker: "YUJA", basePrice: 62, volatility: 0.035 },
  { name: "Yuseong", ticker: "CAPG", basePrice: 50, volatility: 0.035 },
  { name: "Sinu Han", ticker: "SINU", basePrice: 48, volatility: 0.04 },
  { name: "Mandeok Bang", ticker: "BANG", basePrice: 52, volatility: 0.035 },
  { name: "Seongji Yuk", ticker: "6KNG", basePrice: 60, volatility: 0.04 },
  { name: "Vasco", ticker: "VSCO", basePrice: 54, volatility: 0.04 },
  { name: "Vin Jin", ticker: "VIN", basePrice: 55, volatility: 0.045 },
  { name: "Daniel Park", ticker: "LDNL", basePrice: 78, volatility: 0.05 },
  { name: "Lang Jin", ticker: "WOLF", basePrice: 55, volatility: 0.03 },
  { name: "Changsu Oh", ticker: "DOTS", basePrice: 75, volatility: 0.06 },
  { name: "Jichang Kwak", ticker: "SNEK", basePrice: 55, volatility: 0.03 },
  { name: "J", ticker: "COP", basePrice: 75, volatility: 0.06 },
  { name: "Seokdu Wang", ticker: "HDBT", basePrice: 48, volatility: 0.06 },
  { name: "Zack Lee", ticker: "ZACK", basePrice: 53, volatility: 0.04 },
  { name: "Warren Chae", ticker: "CHAE", basePrice: 50, volatility: 0.04 },
  { name: "Hudson Ahn", ticker: "AHN", basePrice: 54, volatility: 0.035 },
  { name: "Gongseop Ji", ticker: "GONG", basePrice: 60, volatility: 0.035 },
  { name: "Ryuhei Kuroda", ticker: "NOMN", basePrice: 50, volatility: 0.04 },
  { name: "Jay Hong", ticker: "JAY", basePrice: 30, volatility: 0.03 },
  { name: "Logan Lee", ticker: "LOGN", basePrice: 30, volatility: 0.05 },
  { name: "Eugene", ticker: "WRKR", basePrice: 26, volatility: 0.03 },
  { name: "Crystal Choi", ticker: "CRYS", basePrice: 25, volatility: 0.03 },
  { name: "Xiaolung", ticker: "XIAO", basePrice: 24, volatility: 0.04 },
  { name: "Jerry Kwon", ticker: "SWRD", basePrice: 50, volatility: 0.035 },
  { name: "Olly Wang", ticker: "OLLY", basePrice: 20, volatility: 0.04 },
  { name: "Brad Lee", ticker: "BRAD", basePrice: 18, volatility: 0.035 },
  { name: "Jason Yoon", ticker: "JSN", basePrice: 16, volatility: 0.04 },
  { name: "Lineman", ticker: "LINE", basePrice: 35, volatility: 0.03 },
  { name: "Jace Park", ticker: "JACE", basePrice: 14, volatility: 0.035 },
  { name: "Sally Park", ticker: "SLLY", basePrice: 13, volatility: 0.03 },
  { name: "Mira Kim", ticker: "MIRA", basePrice: 12, volatility: 0.03 },
  { name: "Zoe Park", ticker: "ZOE", basePrice: 11, volatility: 0.03 },
  { name: "Doo Lee", ticker: "DOO", basePrice: 10, volatility: 0.04 },
  { name: "Jiho Park", ticker: "JIHO", basePrice: 7, volatility: 0.06 },
];

// Create a map for quick lookup
export const CHARACTER_MAP = {};
CHARACTERS.forEach(c => {
  CHARACTER_MAP[c.ticker] = c;
});
